import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from '@/components/Header';
import Footer from "@/components/Footer";
import Form from "@/components/Form";
import Legend from "@/components/Legend";
import List from "@/components/List";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smartfit - Frontend Challenge",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex flex-col">
          <Form />
          <Legend />
          <List />
        </main>
        <Footer />
      </body>
    </html>
  );
}
