import Footer from '@/components/Footer'
import Form from '@/components/Form'
import Header from '@/components/Header'
import Legend from '@/components/Legend'
import List from '@/components/List'

import './globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Smartfit - Frontend Challenge',
  description: 'Generated by create next app'
}

export default function RootLayout() {
  return (
    <html lang='en'>
      <body className='gotham'>
        <Header />
        <main className='flex flex-col'>
          <Form />
          <Legend />
          <List />
        </main>
        <Footer />
      </body>
    </html>
  )
}
