import Footer from '@/components/Footer'
import Header from '@/components/Header'

import './globals.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Smartfit - Frontend Challenge',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className='gotham'>
        <Header />
        <main className='flex flex-col max-w-screen-xl m-auto w-full'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
